databases:
  - name: driver-drowsiness-db
    databaseName: driver_drowsiness
    user: driver_drowsiness

services:
  - type: web
    name: driver-drowsiness-detection-system
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn drowsiness_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: driver-drowsiness-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: "3.10.14"
