# Generated by Django 5.2.13 on 2026-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrowsinessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Awake', 'Awake'), ('Drowsy', 'Drowsy')], max_length=10)),
                ('ear_value', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
